server:
  port: 9090

ai:
  apiKey: "0c83f9963f0a05a9b956650ca7ad12b2.gdxgjndzLA0RpkTH"
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    ai
    username: root
#    10.96.187.151
    password: 123456
#    url: jdbc:mysql://1.12.238.137:3306/lzk?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/lzk?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
#      host: 1.12.238.137
      host: localhost
      port: 6379
      timeout: 6000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

#fileBaseUrl: http://1.12.238.137:${server.port}
fileBaseUrl: http://localhost:${server.port}
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.common.controller
wx:
  appid: wx2fea85e7745d8e75
  secret: 84df404233421ee01280948c0f491483
